@echo off
echo Starting install requirements file...
echo  Auth-Service : installing...
cd "auth-service"
npm i
echo  Order-Service : installing...
cd ..
cd "order-service"
npm i
echo  Product-Service : installing...
cd ..
cd "product-service"
npm i
echo  User-Service : installing...
cd ..
cd "user-service"
npm i
echo  installing finished...