openapi: 3.0.0
info:
  title: E-Commerce
  version: 1.0.0
servers:
  - url: http://localhost:3000
  - url: http://localhost:3001
  - url: http://localhost:3002
  - url: http://localhost:3003
tags:
  - name: Auth
  - name: User
  - name: Product
  - name: Order
paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: Register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: test3
                password: qw126534
                firstname: Alice
                lastname: Rov
                email: Alice@gmail.com
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: test3
                password: qw126534
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /user/profile:
    get:
      tags:
        - User
      summary: View Profile
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - User
      summary: Create Profile
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                id: 6
                firstname: Alice
                lastname: Rov
                address: >-
                  17/4 Moo.5, Bamroongrat Road, Tambon Pibulsongkram, Amphur
                  Muang, Bangkok, 10400
                email: Alice@gmail.com
                phone: '086235612'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /user/order-history/{user_id}:
    get:
      tags:
        - User
      summary: View Order History
      parameters:
        - name: user_id
          in: path
          schema:
            type: integer
          required: true
          example: '6'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /product/{id}:
    get:
      tags:
        - Product
      summary: View Product by ID
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /product/:
    get:
      tags:
        - Product
      summary: View All Product
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /order/create:
    post:
      tags:
        - Order
      summary: Create Order
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                user_id: 6
                product_id_list:
                  - 1
                  - 3
                  - 4
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /order/cancel:
    put:
      tags:
        - Order
      summary: Cancel Order
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                order_id: 7
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /order/view/{order_id}:
    get:
      tags:
        - Order
      summary: View Order by Order ID
      parameters:
        - name: order_id
          in: path
          schema:
            type: integer
          required: true
          example: '5'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /order/user/{user_id}:
    get:
      tags:
        - Order
      summary: View All Order by User ID
      parameters:
        - name: user_id
          in: path
          schema:
            type: integer
          required: true
          example: '6'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}